version: '3.1'

services:
    blog-adonis-api:
        build:
            context: api
            args:
                - NODE_ENV=development
                - PORT=3333
        command: npm run serve --dev
        tty: true
        ports:
            - "3333:3333"
            - "5858:5858"
            - "9229:9229"
        volumes:
            - ./api:/opt/app:delegated
        environment:
            - NODE_ENV=development

    api:
        build:
            context: nginx
        ports:
            - "80:80"
            - "443:443"

    mariadb:
        build:
            context: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=blog
            - MYSQL_USER=blog
            - MYSQL_PASSWORD=secret
        ports:
            - "3306:3306"
